---
title: "EDA_no_imputation"

output: html_document
---


## EDA

## Load data


```{r}
library(survey)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(VIM)

nhanes_complete = read.csv("nhanes_complete_data.csv")
table(nhanes_complete$svy_year)
```




# selecting variabes
```{r}

nhanes_complete_selected_demo <- nhanes_complete[,c("SEQN",
                                      "svy_year",
                                      "svy_weight_mec",
                                      "svy_psu",
                                      "svy_strata",
                                      "svy_subpop_htn",
                                      "svy_subpop_chol",
                                      "DMDEDUC2",
                                      "INDFMPIR",
                                      "demo_age_cat",
                                      "demo_age_years", 
                                      "demo_gender", 
                                      "demo_race", 
                                      "bp_sys_mean", 
                                      "bp_dia_mean",
                                      "htn_accaha",
                                      "cc_bmi",
                                      "cc_diabetes")]

nhanes_complete_selected_no_diet <- nhanes_complete %>% filter(bp_med_use == "No" & DRQSDIET != 1 &
                                         !is.na(DR1TKCAL) & !is.na(INDFMPIR))

nhanes_complete_selected_no_diet <- nhanes_complete_selected_no_diet[,c("SEQN",
                                      "svy_year",
                                      "svy_weight_mec",
                                      "svy_psu",
                                      "svy_strata",
                                      "svy_subpop_htn",
                                      "svy_subpop_chol",
                                      "DMDEDUC2",
                                      "INDFMPIR",
                                      "demo_age_cat",
                                      "demo_age_years", 
                                      "demo_gender", 
                                      "demo_race", 
                                      "bp_sys_mean", 
                                      "bp_dia_mean",
                                      "htn_accaha",
                                      "cc_bmi",
                                      "cc_diabetes")]

nhanes_complete_selected_no_diet$htn_accaha <- as.factor(nhanes_complete_selected_no_diet$htn_accaha)

temp_vec <-nhanes_complete_selected_demo$htn_accaha %>% as.factor() %>% as.integer()
temp_vec <- temp_vec - 1
nhanes_complete_selected_demo$htn_accaha_numeric <- temp_vec %>% as.integer()



nhanes_complete_selected_no_diet$htn_accaha_numeric <-nhanes_complete_selected_no_diet$htn_accaha %>% as.factor() %>% as.numeric() - 1



nhanes_complete_selected_no_diet <- nhanes_complete_selected_no_diet %>%
  mutate(svy_weight_mec=svy_weight_mec/4,
         svy_psu=svy_psu/4,
         svy_strata=svy_strata/4)

nhanes_complete_selected_demo <- nhanes_complete_selected_demo %>%
  mutate(svy_weight_mec=svy_weight_mec/4,
         svy_psu=svy_psu/4,
         svy_strata=svy_strata/4)

```


## Visualizing missing pattern

```{r}

aggr_plot <- aggr(nhanes_complete_selected_demo, 
                  col=c('navyblue','yellow'), 
                  numbers=TRUE, sortVars=TRUE, 
                  labels=names(data), cex.axis=.7, gap=3, 
                  ylab=c("Histogram of missing data","Pattern"))

```

```{r}

aggr_plot_no_diet <- aggr(nhanes_complete_selected_no_diet, 
                  col=c('navyblue','yellow'), 
                  numbers=TRUE, sortVars=TRUE, 
                  labels=names(data), cex.axis=.7, gap=3, 
                  ylab=c("Histogram of missing data with no diet","Pattern"))

```



## Checking variable distributions

```{r}
design <- svydesign(ids = ~svy_psu, 
                    strata = ~svy_strata, 
                    weights = ~svy_weight_mec, 
                    data = nhanes_complete_selected_demo,
                    nest = TRUE)

```


```{r}

survey_year_table = svytable(~svy_year+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name = nhanes_complete$svy_year %>% table() %>% rownames())
p_value = chisq.test(svytable(~svy_year+htn_accaha, design))$p.value
survey_year_table = survey_year_table %>% mutate(p_value = p_value)

survey_year_table

```


```{r}

# calculating the proportion and mean of the key covariates 

survey_year_table = svytable(~svy_year+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name = nhanes_complete$svy_year %>% table() %>% rownames())
p_value = chisq.test(svytable(~svy_year+htn_accaha, design))$p.value
survey_year_table = survey_year_table %>% mutate(p_value = p_value)


age_table = svytable(~demo_age_cat+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name =  nhanes_complete$demo_age_cat %>% table() %>% rownames())
p_value = chisq.test(svytable(~demo_age_cat+htn_accaha, design))$p.value
age_table = age_table %>% mutate(p_value = p_value)



gender_table = svytable(~demo_gender+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble()%>% mutate(name = nhanes_complete$demo_gender %>% table() %>% rownames())
p_value = chisq.test(svytable(~demo_gender+htn_accaha, design))$p.value
gender_table = gender_table %>% mutate(p_value = p_value)



race_table = svytable(~demo_race+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name = nhanes_complete$demo_race %>% table() %>% rownames())
p_value =chisq.test(svytable(~demo_race+htn_accaha, design))$p.value
race_table = race_table %>% mutate(p_value = p_value) 




bmi_table = svytable(~cc_bmi+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name = nhanes_complete$cc_bmi %>% table() %>% rownames())
p_value =chisq.test(svytable(~cc_bmi+htn_accaha, design))$p.value
bmi_table = bmi_table %>% mutate(p_value = p_value) 




diabetes_table = svytable(~cc_diabetes+htn_accaha, design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name = nhanes_complete$cc_diabetes %>% table() %>% rownames()) 
p_value =chisq.test(svytable(~cc_diabetes+htn_accaha, design))$p.value
diabetes_table = diabetes_table %>% mutate(p_value = p_value)


education_table = svytable(~DMDEDUC2+htn_accaha,design) %>% prop.table() %>% as.data.frame.matrix() %>% as_tibble() %>% mutate(name = nhanes_complete$DMDEDUC2 %>% table() %>% rownames())
p_value =chisq.test( svytable(~DMDEDUC2+htn_accaha,design))$p.value
education_table = education_table %>% mutate(p_value = p_value)


design_income_complete <- subset(design,!is.na(INDFMPIR)) 

income_table = svyby(~INDFMPIR,~htn_accaha, design_income_complete,svymean) %>% as.data.frame.matrix() %>% as_tibble()
income_table = t(income_table[,-1]) %>% as_tibble() %>% mutate(name = "Income Level")


# combinging all the tibbles vertically and write them into csv

# bind_rows(list(survey_year_table,age_table,gender_table,race_table,
#                bmi_table,diabetes_table,education_table,income_table)) %>% write.csv("table_one.csv")



```




## Change of Key Demo and Health variables through survey years



```{r}

# svybarplot(demo_race~svy_year,design,col = "skyblue", border = "darkblue")
# title("Race chages through the years")

# Race changes through survey years

race_table <- svytable(~demo_race+svy_year,design) %>% prop.table()
race_table <- race_table / apply(race_table,2,sum)

race_table_df <- as.data.frame(race_table)


race_histogram<-ggplot(race_table_df,aes(x=svy_year,y=Freq,fill=demo_race))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_minimal()+
  labs(x="Survey_year",y="Frequency",fill="Race",title="Changes of Race through survey years")+
  scale_fill_brewer(palette = "Set1") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5))

# Gender changes through survey years, gender variable: demo_gender

gender_table <- svytable(~demo_gender+svy_year,design) %>% prop.table()
gender_table <- gender_table / apply(gender_table,2,sum)

gender_table_df <- as.data.frame(gender_table)


gender_histogram<-ggplot(gender_table_df,aes(x=svy_year,y=Freq,fill=demo_gender))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_minimal()+
  labs(x="Survey_year",y="Frequency",fill="gender",title="Changes of gender through survey years")+
  scale_fill_brewer(palette = "Dark2") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5))


# Age changes through survey years, age variable: demo_age_cat

age_table <- svytable(~demo_age_cat+svy_year,design) %>% prop.table()
age_table <- age_table / apply(age_table,2,sum)

age_table_df <- as.data.frame(age_table)


age_histogram<-ggplot(age_table_df,aes(x=svy_year,y=Freq,fill=demo_age_cat))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_minimal()+
  labs(x="Survey_year",y="Frequency",fill="Age",title="Changes of Age through survey years")+
  scale_fill_manual(values = c("pink", "green", "blue", "black")) +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5))


# BMI changes through survey years, BMI variable: cc_bmi

bmi_table <- svytable(~cc_bmi+svy_year,design) %>% prop.table()
bmi_table <- bmi_table / apply(bmi_table,2,sum)

bmi_table_df <- as.data.frame(bmi_table)


bmi_histogram<-ggplot(bmi_table_df,aes(x=svy_year,y=Freq,fill=cc_bmi))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_minimal()+
  labs(x="Survey_year",y="Frequency",fill="BMI",title="Changes of BMI through survey years")+
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5))



# Diabetes changes through survey years, Diabetes variable: cc_diabetes

diabetes_table <- svytable(~cc_diabetes+svy_year,design) %>% prop.table()
diabetes_table <- diabetes_table / apply(diabetes_table,2,sum)

diabetes_table_df <- as.data.frame(diabetes_table)


diabetes_histogram<-ggplot(diabetes_table_df,aes(x=svy_year,y=Freq,fill=cc_diabetes))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_minimal()+
  labs(x="Survey_year",y="Frequency",fill="Diabetes",title="Changes of Diabetes through survey years")+
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5))


# Hypertension changes through years, binary variable: htn_accaha

htn_table <- svytable(~htn_accaha+svy_year,design) %>% prop.table()
htn_table <- htn_table / apply(htn_table,2,sum)

htn_table_df <- as.data.frame(htn_table)


htn_histogram<-ggplot(htn_table_df,aes(x=svy_year,y=Freq,fill=htn_accaha))+
  geom_bar(stat="identity",position=position_dodge())+
  theme_minimal()+
  labs(x="Survey_year",y="Frequency",fill="Hypertension",title="Changes of Hypertension through survey years")+
  theme(plot.title = element_text(hjust = 0.5, face = "bold"),
        plot.subtitle = element_text(hjust = 0.5))


#library(patchwork)

combined_hist<-race_histogram+gender_histogram+
  age_histogram+bmi_histogram+diabetes_histogram+htn_histogram+
  plot_layout(ncol=2) +
  theme(plot.title = element_text(size = 14), 
                      legend.position = "bottom")

ggsave("combined_histograms.png", combined_hist, width = 16, height = 12)


```

```{r}

year_vec <- nhanes_complete$svy_year %>% table() %>% names()

nhanes_complete_selected_2011 <- nhanes_complete_selected_demo %>% filter(svy_year == year_vec[1])
nhanes_complete_selected_2013 <- nhanes_complete_selected_demo %>% filter(svy_year == year_vec[2])
nhanes_complete_selected_2015 <- nhanes_complete_selected_demo %>% filter(svy_year == year_vec[3])
nhanes_complete_selected_2017 <- nhanes_complete_selected_demo %>% filter(svy_year == year_vec[4])


design_2011 <- svydesign(ids = ~svy_psu, 
                    strata = ~svy_strata, 
                    weights = ~svy_weight_mec, 
                    data = nhanes_complete_selected_2011,
                    nest = TRUE)

design_2013 <- svydesign(ids = ~svy_psu,
                    strata = ~svy_strata,
                    weights = ~svy_weight_mec,
                    data = nhanes_complete_selected_2013,
                    nest = TRUE)

design_2015 <- svydesign(ids = ~svy_psu,
                    strata = ~svy_strata,
                    weights = ~svy_weight_mec,
                    data = nhanes_complete_selected_2015,
                    nest = TRUE)

design_2017 <- svydesign(ids = ~svy_psu,
                    strata = ~svy_strata,
                    weights = ~svy_weight_mec,
                    data = nhanes_complete_selected_2017,
                    nest = TRUE)

```



```{r}

# svyglm(htn_accaha_numeric~demo_age_cat+demo_gender+demo_race+cc_bmi+cc_diabetes,design_2011,family=binomial) %>% summary() %>% coef() %>% data.frame()
# 
# 
# svyglm(htn_accaha_numeric~demo_age_cat+demo_gender+demo_race+cc_bmi+cc_diabetes,design_2013,family=binomial) %>% summary() %>% coef() %>% data.frame()


model = svyglm(htn_accaha_numeric~svy_year*(demo_age_cat+demo_gender+demo_race+cc_bmi+cc_diabetes),design,family=binomial)

model %>% summary() 

```

```{r}

model %>% confint()

```





